
# # # !! BUN
# version: '3.8'

# services:
#   mysql:
#     image: mysql:8
#     container_name: chat-mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpass
#       MYSQL_DATABASE: chat_db
#       MYSQL_USER: chat_user
#       MYSQL_PASSWORD: chat_pass
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./init:/docker-entrypoint-initdb.d  # Aici ai `chat_db.sql`
#       - chat-mysql-data:/var/lib/mysql

#   backend:
#     build: ./apps/chat/backend
#     container_name: chat-backend
#     ports:
#       - "88:88"
#     environment:
#       DB_HOST: mysql
#       DB_PORT: 3306
#       DB_USER: chat_user
#       DB_PASS: chat_pass
#       DB_NAME: chat_db
#     depends_on:
#       - mysql

#   frontend:
#     build: ./apps/chat/frontend
#     container_name: chat-frontend
#     ports:
#       - "90:90"
#     depends_on:
#       - backend

# volumes:
#   chat-mysql-data:


version: '3.8'

services:
  chat-mysql:
    image: mysql:8
    container_name: chat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: chat_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - chat-mysql-data:/var/lib/mysql

  joomla-mysql:
    image: mysql:8
    container_name: joomla-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla_user
      MYSQL_PASSWORD: joomla_pass
    ports:
      - "3307:3306"  # Port diferit pentru a evita conflictul cu chat-mysql
    volumes:
      - joomla-mysql-data:/var/lib/mysql

  backend:
    build: ./apps/chat/backend
    container_name: chat-backend
    ports:
      - "88:88"
    environment:
      DB_HOST: chat-mysql
      DB_PORT: 3306
      DB_USER: chat_user
      DB_PASS: chat_pass
      DB_NAME: chat_db
    depends_on:
      - chat-mysql

  frontend:
    build: ./apps/chat/frontend
    container_name: chat-frontend
    ports:
      - "90:90"
    depends_on:
      - backend

  joomla:
    image: joomla:latest
    container_name: joomla
    restart: always
    ports:
      - "80:80"
    environment:
      JOOMLA_DB_HOST: joomla-mysql
      JOOMLA_DB_USER: joomla_user
      JOOMLA_DB_PASSWORD: joomla_pass
      JOOMLA_DB_NAME: joomla_db
    depends_on:
      - joomla-mysql
    volumes:
      - joomla-data:/var/www/html

volumes:
  chat-mysql-data:
  joomla-mysql-data:
  joomla-data: